---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: non-resource-url-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: non-resource-url-role
subjects:
  - kind: ServiceAccount
    name: controller-manager
    namespace: system
