---
# permissions to create a serviceaccount/token
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: serviceaccount-token-role
rules:
  - apiGroups:
      - ""
    resources:
      - serviceaccounts/token
    verbs:
      - create
